
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_ProcessInstances
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TBL_ProcessInstances()
    {

        this.TBL_ProcessInstances1 = new HashSet<TBL_ProcessInstances>();

    }


    public long ProcessInstanceId { get; set; }

    public string ProcessId { get; set; }

    public Nullable<System.DateTime> CreatedTS { get; set; }

    public Nullable<long> ParentProcessInstanceId { get; set; }

    public Nullable<bool> IsCompleted { get; set; }

    public string AllocatedServer { get; set; }

    public Nullable<System.DateTime> AllocatedTS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBL_ProcessInstances> TBL_ProcessInstances1 { get; set; }

    public virtual TBL_ProcessInstances TBL_ProcessInstances2 { get; set; }

}

}
