
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_BotInfo
{

    public string BotId { get; set; }

    public string ResponseQueueName { get; set; }

    public string RequestQueueName { get; set; }

    public string MachineName { get; set; }

    public Nullable<int> MaxBotQueue { get; set; }

    public Nullable<System.DateTime> CreatedTS { get; set; }

    public Nullable<System.DateTime> ModifiedTS { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
