
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_InvoiceDetail
{

    public string AirlineGSTNumber { get; set; }

    public string InvoiceNumber { get; set; }

    public string InvoiceDate { get; set; }

    public long ProcessInstanceId { get; set; }

}

}
