
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_MessageTracker
{

    public string MessageID { get; set; }

    public Nullable<int> RetrySequence { get; set; }

    public string Status { get; set; }

    public string RequestJsonData { get; set; }

    public string ResponseJsonData { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public string BotID { get; set; }

    public long ProcessInstanceID { get; set; }

    public int Sequence { get; set; }

    public Nullable<int> IncrementTimeout { get; set; }

}

}
