
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_Processes
{

    public string ProcessId { get; set; }

    public string ProcessDescription { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
