
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_ProcessExecution_Settings
{

    public string ProcessId { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.DateTime> EndData { get; set; }

    public Nullable<bool> IsComplete { get; set; }

    public long Id { get; set; }

    public Nullable<long> ProcessInstanceId { get; set; }

    public Nullable<System.DateTime> RequestDate { get; set; }

}

}
