
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_ProcessInstanceError
{

    public Nullable<long> ProcessInstanceId { get; set; }

    public string StateId { get; set; }

    public string MetaData { get; set; }

    public Nullable<System.DateTime> CreateTS { get; set; }

    public long Id { get; set; }

}

}
