
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer.DBModel
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_ProcessInstanceDetails
{

    public long ProcessInstanceId { get; set; }

    public int SequenceId { get; set; }

    public string StateId { get; set; }

    public Nullable<bool> IsCompleted { get; set; }

    public Nullable<System.DateTime> CreateTS { get; set; }



    public virtual TBL_States TBL_States { get; set; }

}

}
